### ISSUE TITLE
Question on pretrained weights

### ISSUE THREAD

**Issue by thorstenwagner** [experiencor/basic-yolo-keras#126]
Hi @experiencor ,

I've a question regarding the pretrained weights loaded in the backend. 
The one layer doing the classification is randomly initialized and during training the magnitude of modifications should be large. The pretrained weights of the backend layers (e.g. Full Yolo) are not frozen. I'm wondering why the weights of the backend are not destroyed due to the large modifications in the classification layer? Moreover, I've to rename the first layer in the backend because I'm using single channel images. That means for the first layer that there are no pretained weights available.  

Considering all this, I am surprised that the net works very well on unseen data even with a very small amount of training data (~ 15 Images, 4096x4096, ~ 100 objects per images, only one class).

Maybe you can share some insights.

Best,
Thorsten

**Comment by experiencor** [comment]
@thorstenwagner Interesting observations but I'm not so sure of this effectiveness. You may want to read http://karpathy.github.io/2015/05/21/rnn-effectiveness/ for some insights.

Regarding the size of the dataset, I think that your dataset is not that small.

In YOLO, we divide the image into cells and we are actually training the anchors in each cell to fit the objects. So I think that it's more appropriate to count the number of object examples that the anchors aim to fit, rather than the number of images. In this respect, your dataset is not that small. It's 1500 learning examples in all the images.

**Comment by experiencor** [comment]
@thorstenwagner You are very right the weight of the last layer (the detection or classification layer). If it's too big, it will destroy the pretrained backend and often result in NaN lass. That's why in line 77 and 78 I need to scale down their values using the size of its input. 

Regarding the weight of the first modified layer, the fact is that the first layer of a CNN would tend to form some kinds of edge detectors **regardless** of the output signal (even random output). So you run the training long enough, it would become a bunch of edge detectors anyway. This is mentioned in some lecture of Introduction to Convolutional Neural Networks for Visual Recognition - Standford. I don't know why it is the case though.

And I think that your dataset is not that small. In YOLO, we divide an image into grid cells and aim to fit 5 or so anchors in each cell to the object examples. So if we count the number of object examples as learning examples, we will have 1.5K examples for the network to learn in all the images.

**Comment by thorstenwagner** [comment]
Thank you very much for your clarifications!
