### ISSUE TITLE
4 coordinates of bounding box instead of 4 (xmin, xmax, ymin, ymax)

### ISSUE THREAD

**Issue by khoaprogrammer** [experiencor/basic-yolo-keras#15]
my dataset was annotated by 4 coordinates instead of 4. How can i change the code to make it works?? Thank you!

**Comment by experiencor** [comment]
I think you should try to convert the 4 coordinates to the (xmin, xmax, ymin, ymax) rather than try to change the code. Changing the code will definitely incur more cost. An valid annotation in VOC format looks like this ([https://github.com/datitran/raccoon_dataset/blob/master/annotations/raccoon-1.xml](https://github.com/datitran/raccoon_dataset/blob/master/annotations/raccoon-1.xml))

**Comment by khoaprogrammer** [comment]
Yeah, i think about convert the coordinates but the problem here is the bounding box is some kind of rotated. So i think that if i want to use your code, i have to annotate them again :(

**Comment by khoaprogrammer** [comment]
and by the way, are you a vietnamese????? :)

**Comment by experiencor** [comment]
Yes, I am a Vietnamese :D. BTW, YOLO, as well as all other methods, only work with (xmin, xmax, ymin, ymax) format.

**Comment by khoaprogrammer** [comment]
Thank you so much! I'm working on a school project with this! Your code is very easy to understand for me! :)
