### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: '../logs/yolo/

### ISSUE THREAD

**Issue by ManjeeraJagiri** [experiencor/basic-yolo-keras#5]
Any idea how to proceed?
I receive this error when I run the following section of the code --
tb_counter  = max([int(num) for num in os.listdir('../logs/yolo/')] or [0]) + 1
tensorboard = TensorBoard(log_dir='../logs/yolo/' + str(tb_counter), histogram_freq=0, write_graph=True, write_images=False)

sgd = SGD(lr=0.00001, decay=0.0005, momentum=0.9)

model.compile(loss=custom_loss, optimizer=sgd)#'adagrad')
model.fit_generator(data_gen(all_img, BATCH_SIZE), 
                    int(len(all_img)/BATCH_SIZE), 
                    epochs = 100, 
                    verbose = 2,
                    callbacks = [early_stop, checkpoint, tensorboard], 
                    max_q_size = 3)

**Comment by experiencor** [comment]
I assume that the error was caused by the missing log folder of tensorboard. You may try to run the following snippet instead.

`#tb_counter = max([int(num) for num in os.listdir('../logs/yolo/')] or [0]) + 1
#tensorboard = TensorBoard(log_dir='../logs/yolo/' + str(tb_counter), histogram_freq=0, write_graph=True, write_images=False)

sgd = SGD(lr=0.00001, decay=0.0005, momentum=0.9)

model.compile(loss=custom_loss, optimizer=sgd)#'adagrad')
model.fit_generator(data_gen(all_img, BATCH_SIZE),
int(len(all_img)/BATCH_SIZE),
epochs = 100,
verbose = 2,
callbacks = [early_stop, checkpoint],#, tensorboard],
max_q_size = 3)`

**Comment by ManjeeraJagiri** [comment]
Yes it worked! The training is going on. I assume it will take a long time as I am running it on a CPU. Thanks a lot!!
